### ISSUE TITLE
Оценивание

### ISSUE THREAD

**Issue by gerra** [IFMO-MobDev-2014/colloquium3#22]
Buy/sell : 8
Если сделано 2/3 от первого пункта (lisview, service, contentprovider), то эти 8 баллов всё равно возможно получить?

**Comment by thevery** [comment]
А какой части не хватает до обязательных 6 баллов?

**Comment by gerra** [comment]
сервиса :(

**Comment by thevery** [comment]
тогда точно 0 - остальное-то делается по сути копи-пейстом из прошлых дз
